### ISSUE TITLE
Update for 3.2 coming?

### ISSUE THREAD

**Issue by steven850** [p2or/blender-dof-utils#5]
Will you be updating the add on for blender 3.xx??

**Comment by p2or** [comment]
Hi @steven850,

The current version of the add-on already works in Blender 3.2+. Nothing to update as far as I can see:

<img width="1193" alt="yeah" src="https://user-images.githubusercontent.com/512368/175592795-2e62976d-9a7f-49a2-b9ec-49cecb77627e.png">

Closing for now. If something else comes up, just let me know.

Cheers,
Christian

**Comment by steven850** [comment]
I install the addon but it never shows in the addons list. Its says it was added but it doesnt show in the list to enable it, so I assumed it was not compatible with 3.2. Any ideas why its now showing up?
[system-info.txt](https://github.com/p2or/blender-dof-utils/files/8978554/system-info.txt)

**Comment by p2or** [comment]
Hi @steven850,

I guess you have downloaded the code of the repository by using the green code button...? If so, just download the py-file from from the [releases page](https://github.com/p2or/blender-dof-utils/releases). Also see the [installation instructions](https://github.com/p2or/blender-dof-utils#installation) for more details.

Cheers,
Christian

**Comment by steven850** [comment]
Just tried it on 3 other machines, same result...

**Comment by steven850** [comment]
Thats my bad.......   I installed from zip like with all other addons, didnt see you set it up to install the .py directly. Sorry about that.

**Comment by p2or** [comment]
No problem, have fun with it. Cheers 🎉
