### ISSUE TITLE
OpenGL / Metal / GPU  issue

### ISSUE THREAD

**Issue by nurb2kea** [p2or/blender-dof-utils#6]
Hi,
as far as I know all addons need to switch to Metal...

I found this information. May it be helpful:

The blender dev’s reccomended to ask https://projects.blender.org/mano-wii
and look at this case to get more info on this to fix addons.
[https://projects.blender.org/blender/blender-addons/commit/5c22e77ea30327173d542b41dc2f7653f2cb1a7a 1](https://projects.blender.org/blender/blender-addons/commit/5c22e77ea30327173d542b41dc2f7653f2cb1a7a)

EDIT: More info !

There are two reasons why shaders needs to be ported:

Addon still uses bgl that call OpenGL calls directly.
Shader don’t use gpu.types.ShaderCreateInfo to support cross platform source generation.
These structures have already been in place for some time, and we communicated that addon developers should use this new API. It is sadly common for developers to only port to newer API’s when it makes sense for them.

In this case it looks like he hasn’t ported his shaders to use gpu.types.ShaderCreateInfo as described on https://docs.blender.org/api/current/gpu.html. If someone requires some help they can get in contact with the Eevee/viewport module at blender.chat or in the python channel. I am happy to help out there.

![Screenshot 2023-04-03 at 5 11 52 am](https://user-images.githubusercontent.com/57676085/229404836-1f95aa72-a0a0-4ece-8baf-7c6955051e57.jpg)

**Comment by p2or** [comment]
Hi @nurb2kea,

thanks for your report. I created a new branch to address this issue and replaced all [deprecated `bgl` calls](https://github.com/p2or/blender-dof-utils/commit/6c172869bba6c0009e3558c4273dc9d29b1c2ed4) to get rid of the warnings: https://github.com/p2or/blender-dof-utils/tree/Blender-3.5+ If you have the time, please download the add-on from there and report back.

Cheers,
Christian

**Comment by nurb2kea** [comment]
Hi,

Wohoo, just tested it with blender 3.5 & 3.6 (MacOS 13.3.1) && the 'Info message' is gone and addon works fine in both versions.

Thank you very much for your support and time. :-)

**Comment by p2or** [comment]
Ez, glad I could help. Cheers, Christian
